c_compiler:
- vs2019  # [win]
cxx_compiler:
- vs2019  # [win]
# need a minimum macOS that is higher than conda-forge default to support std::filesystem
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
