travis:
  secure:
    BINSTAR_TOKEN: FSbIVIXrLPzK7Hh0s4ul9sPtjTI8jcuDhwvx19HGPGr1EtOXHdYr4QcArC2YtPZc6fvaKxRLtnUbEVEjmjcaSt25RNQwMZvsNCwNC1B3pt/gAIqzXMMjuVskCz2Bz1sr1qF2Z4nixD5zI2j92rVniSvs4ZluWVCHiTS8JqvVbw0UTqArtHKr+EnPFf5GLKdKkQkOS4DMFctUBZdGgBoK7rgXrG0VkWTVR5WWep3Jaf94mNDmnSu8+N34r/TaZZcveohQLr8AoHd6+yocsYTonCZU0zS+QbgAEUPoYPYZki9mCR/dvEDEk0IizYeJVBfP1EPDEExrf+OxseqsdUdCKl9a7DEyBu3efgzGy0MOj+T4ECemnKmv2InVAhJ9jOhW++Ks0/dxzoch3dEBQDWSleKJq0xjnywZg9M0enTVdFN3BYRldOfBlfoHfJjPJcgUVEoUYxRtrQt0D0t4K9bxzYBOKByMna0eVinDrQ6cgzOPytU+zOJ3NLFyCvnAFseN0fvtv09gBY78KPvaOv4E8HxHU2beegRumxWBHSn6Xz37mkikSRlfrrgXqPRcgGBURf58KZ7H0GqRJz95YC0ivClHnOi5Hv/RgGu90Lqzhfch5FmYHhettH3uBtsUAQffZPvo8RD1gVLV3N+CIkGFz3tyE+NgnWHph71kjHBIvbE=
conda_forge_output_validation: true
bot:
  automerge: true
